name: Outdated dependencies check
on:
  workflow_call:
    inputs:
      YARN:
        default: false
        type: boolean
      YARN_SLACK_CHANNEL:
        required: false
        type: string
      BUNDLER:
        default: false
        type: boolean
      BUNDLER_SLACK_CHANNEL:
        required: false
        type: string
jobs:
  check-yarn-outdated-dependencies:
    runs-on: ubuntu-latest
    if: ${{inputs.YARN}}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - id: yarn-outdated
        run: yarn outdated > yarn_outdated.txt
        continue-on-error: true
      - name: Print file content
        run: cat yarn_outdated.txt
      - if: steps.yarn-outdated.outcome == 'failure'
        run: |
          curl \
          -F file=@yarn_outdated.txt \
          -F "initial_comment=\`yarn outdated\` on ${{github.repository}}" \
          -F channels=${{inputs.YARN_SLACK_CHANNEL}} \
          -H "Authorization: Bearer ${{secrets.SLACK_PACKAGE_UPDATE_BOT_SECRET}}" \
          https://slack.com/api/files.upload
  check-bundle-outdated-dependencies:
    runs-on: ubuntu-latest
    if: ${{inputs.BUNDLER}}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Set up ruby
        uses: ruby/setup-ruby@v1.134.0
        with:
          ruby-version: '.tool-versions'
      - run: make -f .ci/Makefile update-bundle
      - run: bundle outdated > bundle_outdated.txt
        id: bundle-outdated
        continue-on-error: true
      - name: Print file content
        run: cat bundle_outdated.txt
      - if: steps.bundle-outdated.outcome == 'failure'
        run: |
          curl \
          -F file=@bundle_outdated.txt \
          -F "initial_comment=\`bundle outdated\` on ${{github.repository}}" \
          -F channels=${{inputs.BUNDLER_SLACK_CHANNEL}} \
          -H "Authorization: Bearer ${{secrets.SLACK_PACKAGE_UPDATE_BOT_SECRET}}" \
          https://slack.com/api/files.upload
