name: Semver label checker
on:
  workflow_call:

jobs:
  semver-label-check:
    name: Check semver label
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:v1.4.25
        with:
          one_of: major,minor,patch
          repo_token: ${{ secrets.GITHUB_TOKEN }}
